language: node_js

node_js:
  - node

script:
  - make lint

before_script:
  - npm install babel-cli -S

deploy:
  provider: npm
  email: "kiriliuss@mail.ru"
  api_key: "440ba389-5aac-45eb-a17c-d8f5a90f94b0"